### ISSUE TITLE
Null pointer exception

### ISSUE THREAD

**Issue by DrLaurenCWhite** [amyko/clapper#3]
Hi again,
I am having trouble with a different error, this time from java. I have posted the stdout below.
Thank you for your time
-Lauren

Preprocessing...
RefPop not given. Setting refPopFileName = fileName
Computing marginal likelihoods...
Exception in thread "main" java.lang.NullPointerException
        at likelihood.PairwiseLikelihoodCoreStreamPed.computePossibleConditionalGenotypeProbWithError(PairwiseLikelihoodCoreStreamPed.java:1248)
        at likelihood.PairwiseLikelihoodCoreStreamPed.computeMarginal(PairwiseLikelihoodCoreStreamPed.java:293)
        at executables.Run.computeMarginals(Run.java:150)
        at executables.Run.computeLikelihoods(Run.java:95)
        at executables.Run.main(Run.java:307)

**Comment by DrLaurenCWhite** [comment]
This only occurs when I have #conditiononld set to 0. 
I can replicate the error in the test data.
